LABEL Arch Linux ARM
KERNEL /Image
FDT /dtbs/rockchip/rk3399-orangepi-800.dtb
APPEND initrd=/initramfs-linux.img earlycon=uart8250,mmio32,0xff1a0000 console=ttyS2,1500000 root=/dev/mmcblk1p2 rw rootwait
